CREATE TABLE IF NOT EXISTS Shops (
    id_shop INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name_shop VARCHAR(255) NOT NULL,
    adr_shop VARCHAR(255) NOT NULL,
    tel_shop INT NOT NULL
    );

CREATE TABLE IF NOT EXISTS Users (
    id_user INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    contact INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Bookings (
    id_booking INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name_shop VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Slots (
    id_creneau INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    date_in DATE NOT NULL,
    date_out DATE NOT NULL,
    time DATE NOT NULL
);